---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: env-state
- name: paving

outputs:
- name: env

run:
  path: paving/ci/tasks/write-env-yml/task
