---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: env-state
- name: paving

outputs:
- name: env-state

run:
  path: paving/ci/tasks/get-ops-manager-config/task

params:
  IAAS:

  GCP_SERVICE_ACCOUNT_KEY:

  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:

  AZURE_TENANT_ID:
  AZURE_SUBSCRIPTION_ID:
  AZURE_CLIENT_ID:
  AZURE_CLIENT_SECRET:
