---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: paving-ci
- name: opsman-image

outputs:
- name: tfvars

run:
  path: paving-ci/ci/tasks/latest-opsman/task

# IAAS:
params:
  # AWS|GCP|Azure
  IAAS: ""
  # For AWS use one of the supported AWS regions (e.g. us-west-1)
  # For GCP use 'us', 'eu' or 'asia'
  # For Azure use  one of the supported Azure regions (e.g. west_us)
  KEY: ""
